################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andrés                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
    name: nlb-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            service: nlb-svc
    template:
        metadata:
            labels:
                service: nlb-svc
        spec:
            containers:
            -
                image: "alejandrocolomar/nginx:1.9.1-custom"
                livenessProbe:
                    httpGet:
                        path: /
                        port: 30080
                    initialDelaySeconds: 10
                name: nlb-container
                ports:
                -
                    containerPort: 30080
                -
                    containerPort: 31080
                -
                    containerPort: 32080
                readinessProbe:
                    httpGet:
                        path: /
                        port: 30080
                    initialDelaySeconds: 1
                volumeMounts:
                -
                    mountPath: /usr/local/etc/nginx/conf.d/
                    name: etc-nginx-confd-volume
                    readOnly: true
                -
                    mountPath: /usr/local/etc/nginx/
                    name: etc-nginx-volume
                    readOnly: true
                -
                    mountPath: /var/cache/nginx/
                    name: var-cache-nginx-volume
                -
                    mountPath: /var/log/nginx/
                    name: var-log-nginx-volume
                -
                    mountPath: /var/run/
                    name: var-run-volume
            volumes:
            -
                name: etc-nginx-volume
                configMap:
                    name: etc-nginx-cm
            -
                name: etc-nginx-confd-volume
                configMap:
                    name: etc-nginx-confd-cm
            -
                name: var-cache-nginx-volume
                emptyDir: {}
            -
                name: var-log-nginx-volume
                emptyDir: {}
            -
                name: var-run-volume
                emptyDir: {}

