################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andres                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################

configs:
    etc-nginx-nginx-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/nginx.conf
    etc-nginx-conf-d-nlb-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/nlb.conf
    etc-nginx-conf-d-www-ports-test-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_test.conf
    etc-nginx-conf-d-www-ports-stable-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_stable.conf
    etc-nginx-conf-d-www-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www.conf

networks:
    alejandro-colomar:

services:
    nlb:
        configs:
        -
            mode: 0440
            source:  etc-nginx-nginx-conf-nlb-config
            target: /etc/nginx/nginx.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-nlb-conf-nlb-config
            target: /etc/nginx/conf.d/nlb.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-ports-test-conf-nlb-config
            target: /etc/nginx/conf.d/www_ports_test.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-ports-stable-conf-nlb-config
            target: /etc/nginx/conf.d/www_ports_stable.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-conf-nlb-config
            target: /etc/nginx/conf.d/www.conf
        deploy:
            mode: replicated
            placement:
                constraints:
                -   node.role == worker
            replicas: 1
            restart_policy:
                condition: any
        image: "docker.io/alejandrocolomar/nginx:1.16.0@sha256:34c652cbc41b0c09daab213282ab0af88d4a55dd532a98458e221035bdfa6d0d"
        networks:
        -
            "alejandro-colomar"
        ports:
        -   "30080:30080"
        -   "31080:31080"
        volumes:
        -   nlb:/var/log/nginx

version: '3.8'
volumes:
    nlb:
