################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andres                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################

configs:
    nginx_conf:
        file: /run/configs/nlb/etc/nginx/nginx.conf
    nginx_conf_nlb:
        file: /run/configs/nlb/etc/nginx/conf.d/nlb.conf
    nginx_conf_www_ports_exp:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_exp.conf
    nginx_conf_www_ports_rc:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_rc.conf
    nginx_conf_www_ports_stable:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_stable.conf
    nginx_conf_www:
        file: /run/configs/nlb/etc/nginx/conf.d/www_stable.conf

networks:
    alejandro-colomar:

services:
    nlb:
        configs:
        -
            mode: 0440
            source: nginx_conf
            target: /etc/nginx/nginx.conf
        -
            mode: 0440
            source: nginx_conf_nlb
            target: /etc/nginx/conf.d/nlb.conf
        -
            mode: 0440
            source: nginx_conf_www_ports_exp
            target: /etc/nginx/conf.d/www_ports_exp.conf
        -
            mode: 0440
            source: nginx_conf_www_ports_rc
            target: /etc/nginx/conf.d/www_ports_rc.conf
        -
            mode: 0440
            source: nginx_conf_www_ports_stable
            target: /etc/nginx/conf.d/www_ports_stable.conf
        -
            mode: 0440
            source: nginx_conf_www
            target: /etc/nginx/conf.d/www.conf
        deploy:
            placement:
                constraints:
                -   node.role == worker
            replicas: 3
        image: "alejandrocolomar/nginx:1.6.1"
        networks:
        -
            "alejandro-colomar"
        ports:
        -   "30080:30080"
        -   "31080:31080"
        -   "32080:32080"
        volumes:
        -   nlb:/var/log/nginx

version: '3.8'
volumes:
    nlb:
