#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################

configs:
    nginx_conf:
        file: /run/configs/nlb/etc/nginx/nginx.conf
    nginx_conf_nlb:
        file: /run/configs/nlb/etc/nginx/conf.d/nlb.conf
    nginx_conf_security-parameters:
        file: /run/configs/nlb/etc/nginx/conf.d/security-parameters.conf

services:
    nlb:
        configs:
        -
            mode: 0440
            source: nginx_conf
            target: /etc/nginx/nginx.conf
        -
            mode: 0440
            source: nginx_conf_nlb
            target: /etc/nginx/conf.d/nlb.conf
        -
            mode: 0440
            source: nginx_conf_security-parameters
            target: /etc/nginx/conf.d/security-parameters.conf
        deploy:
            placement:
                constraints:
                -   node.role == worker
            replicas: 1
        image: "alejandrocolomar/nginx:1.6.1"
        ports:
        -   "6443:6443"
        volumes:
        -   nlb:/var/log/nginx

version: '3.8'
volumes:
    nlb:
