################################################################################
##      Copyright (C) 2020        Sebastian Francisco Colomar Bauza           ##
##      Copyright (C) 2020        Alejandro Colomar Andres                    ##
##      SPDX-License-Identifier:  GPL-2.0-only                                ##
################################################################################

configs:
    etc-nginx-nginx-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/nginx.conf
    etc-nginx-conf-d-nlb-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/nlb.conf
    etc-nginx-conf-d-www-ports-exp-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_exp.conf
    etc-nginx-conf-d-www-ports-rc-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_rc.conf
    etc-nginx-conf-d-www-ports-stable-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www_ports_stable.conf
    etc-nginx-conf-d-www-conf-nlb-config:
        file: /run/configs/nlb/etc/nginx/conf.d/www.conf

networks:
    alejandro-colomar:

services:
    nlb:
        configs:
        -
            mode: 0440
            source:  etc-nginx-nginx-conf-nlb-config
            target: /etc/nginx/nginx.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-nlb-conf-nlb-config
            target: /etc/nginx/conf.d/nlb.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-ports-exp-conf-nlb-config
            target: /etc/nginx/conf.d/www_ports_exp.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-ports-rc-conf-nlb-config
            target: /etc/nginx/conf.d/www_ports_rc.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-ports-stable-conf-nlb-config
            target: /etc/nginx/conf.d/www_ports_stable.conf
        -
            mode: 0440
            source:  etc-nginx-conf-d-www-conf-nlb-config
            target: /etc/nginx/conf.d/www.conf
        deploy:
            placement:
                constraints:
                -   node.role == worker
            replicas: 3
            restart_policy:
                condition: any
        image: "alejandrocolomar/nginx:1.9.3-2"
        networks:
        -
            "alejandro-colomar"
        ports:
        -   "30080:30080"
        -   "31080:31080"
        -   "32080:32080"
        volumes:
        -   nlb:/var/log/nginx

version: '3.8'
volumes:
    nlb:
