name: CI-docker-swarm

on:
    push:
    pull_request:

jobs:

    swarm:
        env:
            compose: etc/docker/swarm/compose.yaml
            mode: swarm
        runs-on: ubuntu-20.04
        steps:
        -
            name: clone libalx
            run: sudo git -C /usr/local/src clone http://github.com/alejandro-colomar/libalx.git;
        -
            name: install libalx
            run: sudo make -C /usr/local/src/libalx install-sh;
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: init swarm
            run: docker swarm init;
        -
            name: Fix swarm compose for a single machine
            run: sed -i "s/worker/manager/" "${compose}";
        -
            name: deploy
            run: sudo ./bin/containers/deploy.sh "${mode}";
        -
            name: wait Up
            run: |
                while true; do
                    sleep 1;
                    docker service ls |                                 \
                            grep '\([0-9]\)/\1' &&                      \
                            break;
                done
