name: CI-docker-swarm

on:
    push:
    pull_request:

jobs:

    swarm:
        runs-on: ubuntu-20.04
        steps:
        -
            name: git clone alejandro-colomar/containers
            run: |
                sudo git -C /usr/local/src \
                        clone --single-branch --branch 'v0.4.1' \
                        http://github.com/alejandro-colomar/containers.git;
        -
            name: make swarm
            run: sudo make -C /usr/local/src/containers swarm;
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: docker swarm init
            run: docker swarm init --advertise-addr lo;
        -
            name: sed
            run: sed -i "s/worker/manager/" etc/swarm/manifests/compose.yaml;
        -
            name: make stack-deploy
            run: sudo make stack-deploy;
        -
            name: docker service ls
            run: |
                while true; do
                    sleep 1;
                    docker service ls \
                    |grep '\([0-9]\)/\1' \
                        && break;
                done;
